# Generated by Django 5.0.6 on 2024-06-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_explanation',
            field=models.TextField(blank=True),
        ),
    ]
