# Generated by Django 5.0.6 on 2024-07-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_extra_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
    ]
