# Generated by Django 5.0.6 on 2024-07-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_room_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdiscount',
            name='title',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
