# Generated by Django 5.0.6 on 2024-07-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_roomdiscount_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='final_price',
            field=models.IntegerField(default=0),
        ),
    ]
