# Generated by Django 5.0.6 on 2024-07-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cart_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_capacity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
