# Generated by Django 5.0.6 on 2024-07-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cart_total_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
