# Generated by Django 5.0.6 on 2024-07-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_capacity',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
