# Generated by Django 5.0.6 on 2024-07-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
