# Generated by Django 5.0.7 on 2024-07-10 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_order_discount_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_code',
        ),
    ]
