# Generated by Django 5.0.7 on 2024-07-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='discription',
            new_name='description',
        ),
    ]
