# Generated by Django 5.0.7 on 2024-07-17 11:28

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_discription_notification_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='end_date',
            field=django_jalali.db.models.jDateTimeField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=models.ImageField(upload_to='notif/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='start_date',
            field=django_jalali.db.models.jDateTimeField(),
        ),
        migrations.AlterField(
            model_name='roomtypeimage',
            name='image',
            field=models.ImageField(upload_to='roomtype/'),
        ),
    ]
