# Generated by Django 5.0.7 on 2024-07-17 11:43

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_notification_end_date_alter_notification_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='end_booking',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='start_booking',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='customerdiscount',
            name='end',
            field=django_jalali.db.models.jDateTimeField(),
        ),
        migrations.AlterField(
            model_name='customerdiscount',
            name='start',
            field=django_jalali.db.models.jDateTimeField(),
        ),
        migrations.AlterField(
            model_name='customerdiscountusage',
            name='used_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_booking',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='placed_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_booking',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='roomdiscount',
            name='end',
            field=django_jalali.db.models.jDateTimeField(),
        ),
        migrations.AlterField(
            model_name='roomdiscount',
            name='start',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
